import type { Metadata, Viewport } from "next";
import { headers } from "next/headers";
import { ClerkProvider } from "@clerk/nextjs";

import { Header } from "@/components/Header";
import { MessengerProvider } from "@/components/Messenger";

import "katex/dist/katex.min.css";
import "./globals.css";

export const metadata: Metadata = {
  title: { default: "Weightroom", template: "%s · Weightroom" },
  description: "Submit, independently evaluate, and publish open-weight language models.",
  robots: { index: false, follow: false },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  colorScheme: "light",
  themeColor: "#ffffff",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  // Reading request headers keeps the document dynamic so Next can apply the
  // per-request CSP nonce generated by proxy.ts to its framework scripts.
  await headers();
  return (
    <ClerkProvider afterSignOutUrl="/buy">
      <html lang="en">
        <body>
          <a className="skip-link" href="#main-content">Skip to content</a>
          <MessengerProvider>
            <Header />
            <main id="main-content" className="shell page-shell">{children}</main>
          </MessengerProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
